<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.avaje</groupId>
    <artifactId>java11-oss</artifactId>
    <version>5.2</version>
  </parent>

  <groupId>com.zyneonstudios.apex</groupId>
  <artifactId>jauri-webview-parent</artifactId>
  <name>jauri-webview-parent</name>
  <version>0.30</version>
  <packaging>pom</packaging>

  <properties>
    <maven.compiler.release>25</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <modules>
    <module>jauri-webview</module>
  </modules>

  <distributionManagement>
    <repository>
      <id>nerofy-snapshots</id>
      <name>Nerofy Network Maven repository</name>
      <url>https://maven.nrfy.net/snapshots</url>
    </repository>
  </distributionManagement>

  <profiles>
    <profile>
      <id>default</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
  </profiles>
</project>
