<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zyneonstudios.apex</groupId>
        <artifactId>jauri-webview-parent</artifactId>
        <version>0.30</version>
    </parent>
    <version>0.1</version>

    <groupId>io.avaje</groupId>
    <artifactId>examples</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>hello-world</module>
        <module>htmx-jex-bootstrap</module>
        <module>test-window</module>
        <module>todo-basecoat-vue</module>
    </modules>


</project>
